export type RepositoryStatus = 'completed' | 'pending' | 'failed';
export type RepositoryVisibility = 'private' | 'public';

export interface Repository {
  id: number,//410242449,
  node_id?: string,//'R_kgDOGHPNkQ',
  name?: string,//'alibabaserver',
  full_name?: string,//'ntalamdotcom/alibabaserver',
  private?: boolean,//true,
  owner?: {
    login?: string,//'ntalamdotcom',
    id?: number,//61484617,
    node_id?: string,//'MDQ6VXNlcjYxNDg0NjE3',
    avatar_url?: string,//string,//://avatars.githubusercontent.com/u/61484617?v=4',
    gravatar_id?: string,//'',
    url?: string,//string,//://api.github.com/users/ntalamdotcom',
    html_url?: string,//string,//://github.com/ntalamdotcom',
    followers_url?: string,//string,//://api.github.com/users/ntalamdotcom/followers',
    following_url?: string,//string,//://api.github.com/users/ntalamdotcom/following{/other_user}',
    gists_url?: string,//string,//://api.github.com/users/ntalamdotcom/gists{/gist_id}',
    starred_url?: string,//string,//://api.github.com/users/ntalamdotcom/starred{/owner}{/repo}',
    subscriptions_url?: string,//string,//://api.github.com/users/ntalamdotcom/subscriptions',
    organizations_url?: string,//string,//://api.github.com/users/ntalamdotcom/orgs',
    repos_url?: string,//string,//://api.github.com/users/ntalamdotcom/repos',
    events_url?: string,//string,//://api.github.com/users/ntalamdotcom/events{/privacy}',
    received_events_url?: string,//string,//://api.github.com/users/ntalamdotcom/received_events',
    type?: string,//'User',
    site_admin?: boolean,//
  },
  html_url?: string,
  description?: string,//'all the websites ',
  fork?: boolean,//,
  url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver',
  forks_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/forks',
  keys_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/keys{/key_id}',
  collaborators_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/collaborators{/collaborator}',
  teams_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/teams',
  hooks_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/hooks',
  issue_events_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/issues/events{/number}',
  events_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/events',
  assignees_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/assignees{/user}',
  branches_url?: string,//string,//://api.github.com/repos/ntalamdotcom/alibabaserver/branches{/branch}',
  tags_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/tags',
  blobs_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/git/blobs{/sha}',
  git_tags_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/git/tags{/sha}',
  git_refs_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/git/refs{/sha}',
  trees_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/git/trees{/sha}',
  statuses_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/statuses/{sha}',
  languages_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/languages',
  stargazers_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/stargazers',
  contributors_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/contributors',
  subscribers_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/subscribers',
  subscription_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/subscription',
  commits_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/commits{/sha}',
  git_commits_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/git/commits{/sha}',
  comments_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/comments{/number}',
  issue_comment_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/issues/comments{/number}',
  contents_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/contents/{+path}',
  compare_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/compare/{base}...{head}',
  merges_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/merges',
  archive_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/{archive_format}{/ref}', downloads_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/downloads',
  issues_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/issues{/number}',
  pulls_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/pulls{/number}',
  milestones_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/milestones{/number}', notifications_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/notifications{?since,all,participating}',
  labels_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/labels{/name}',
  releases_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/releases{/id}',
  deployments_url?: string,//://api.github.com/repos/ntalamdotcom/alibabaserver/deployments',
  created_at?: Date,
  updated_at?: Date,
  pushed_at?: Date,
  git_url?: string,//://github.com/ntalamdotcom/alibabaserver.git',
  ssh_url?: string,//@github.com:ntalamdotcom/alibabaserver.git',
  clone_url?: string,//://github.com/ntalamdotcom/alibabaserver.git',
  svn_url?: string,//://github.com/ntalamdotcom/alibabaserver',
  homepage?: null,
  size?: number,//367981,
  stargazers_count?: number,//0,
  watchers_count?: number,//0,
  language?: string,//'PHP',
  has_issues?: boolean,//true,
  has_projects?: boolean,//true,
  has_downloads?: boolean,//true,
  has_wiki?: boolean,//,
  has_pages?: boolean,//,
  has_discussions?: boolean,//,
  forks_count?: number,//0,
  mirror_url?: null,
  archived?: boolean,//,
  disabled?: boolean,//,
  open_issues_count?: number,// 0,
  license?: null,
  allow_forking?: boolean,//true,
  is_template?: boolean,//,
  web_commit_signoff_required?: boolean,//,
  topics?: [],
  visibility?: string, //'private',
  forks?: number,//0,
  open_issues?: number,//0,
  watchers?: number,//0,
  default_branch?: string,//'main',
  permissions?: {
    admin?: boolean,//true, maintain?: boolean,//true,
    push?: boolean,//true, 
    triage?: boolean,//true, 
    pull?: boolean,//true
  }
}
